### ISSUE TITLE
mkdirp is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Zipbug** [ianobermiller/nuclearmail#14]
When I try to run the start command it errors out right off the bat with mkdirp is not recognised as an internal or exteral comand. Was this supposed to be mkdir? I tried this on both mac and windows and they both hit the same error. Bellow is the npm_debug log (I removed my name from the path on error 11)

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart nuclearmail@0.0.1
6 info start nuclearmail@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info nuclearmail@0.0.1 Failed to exec start script
9 verbose stack Error: nuclearmail@0.0.1 start: `npm run watch-html & npm run watch-js & npm run serve`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid nuclearmail@0.0.1
11 verbose cwd C:\Users\~~~~~\Documents\nuclearmail-master
12 error Windows_NT 10.0.10586
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.2.4
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error nuclearmail@0.0.1 start: `npm run watch-html & npm run watch-js & npm run serve`
17 error Exit status 1
18 error Failed at the nuclearmail@0.0.1 start script 'npm run watch-html & npm run watch-js & npm run serve'.
18 error This is most likely a problem with the nuclearmail package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run watch-html & npm run watch-js & npm run serve
18 error You can get their info via:
18 error     npm owner ls nuclearmail
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by ianobermiller** [comment]
mkdirp is a module: https://www.npmjs.com/package/mkdirp. I think I ran into this the last time I looked, can't remember how I fixed it, or if I did.

**Comment by Zipbug** [comment]
Hmmm.. I installed mkdirp and nodemon so it get farther when I try to start it, but it now says 'echo' is not recognized.... Is that another package?
